# Generated by Django 3.2.9 on 2021-12-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
